apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.apiGateway.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: {{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: clahanstore-config
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi