apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.cartService.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: {{ .Values.cartService.image.repository }}:{{ .Values.cartService.image.tag }}
        ports:
        - containerPort: 3006
        env:
        - name: PORT
          value: '3006'
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: clahanstore-config
              key: PRODUCT_SERVICE_URL
        - name: INVENTORY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: clahanstore-config
              key: INVENTORY_SERVICE_URL
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: clahanstore-secrets
              key: MONGO_URI_CART
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi