apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.shippingService.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: shipping-service
        image: {{ .Values.shippingService.image.repository }}:{{ .Values.shippingService.image.tag }}
        ports:
        - containerPort: 3011
        env:
        - name: PORT
          value: '3011'
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: clahanstore-config
              key: ORDER_SERVICE_URL
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: clahanstore-secrets
              key: MONGO_URI_SHIPPING
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi