apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  email-username: "your-email@gmail.com"
  email-password: "your-app-password" # Obtain an app-password from Google Account security settings
