apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-backend-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.email: alert@clahanstore.com
    notifications.argoproj.io/subscribe.on-sync-failed.email: alert@clahanstore.com
spec:
  project: default
  source:
    repoURL: 'https://github.com/M-VIGNESH3/E-Commerce-Project.git'
    targetRevision: feature/argo-blue-green
    path: ecommerce-microservices/release
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: clahanstore
  syncPolicy:
    automated:
      prune: false 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
