adminService:
  image:
    repository: busybox
    tag: '1.36'
  replicas: 1
apiGateway:
  image:
    repository: team4devops/ecommerce-api-gateway
    tag: v1.0.0
  replicas: 2
authService:
  image:
    repository: busybox
    tag: '1.36'
  replicas: 2
cartService:
  image:
    repository: busybox
    tag: '1.36'
  replicas: 1
frontendUi:
  image:
    repository: team4devops/ecommerce-frontend-ui
    tag: v1.0.0
  replicas: 2
inventoryService:
  image:
    repository: busybox
    tag: '1.36'
  replicas: 1
invoiceService:
  image:
    repository: busybox
    tag: '1.36'
  replicas: 1
mongodb:
  image:
    repository: mongo
    tag: '6.0'
  replicas: 1
namespace: clahanstore
orderService:
  image:
    repository: busybox
    tag: '1.36'
  replicas: 1
paymentService:
  image:
    repository: busybox
    tag: '1.36'
  replicas: 1
productService:
  image:
    repository: busybox
    tag: '1.36'
  replicas: 2
recommendationService:
  image:
    repository: busybox
    tag: '1.36'
  replicas: 1
reviewRatingService:
  image:
    repository: busybox
    tag: '1.36'
  replicas: 1
searchService:
  image:
    repository: busybox
    tag: '1.36'
  replicas: 1
shippingService:
  image:
    repository: busybox
    tag: '1.36'
  replicas: 1
userService:
  image:
    repository: busybox
    tag: '1.36'
  replicas: 1
wishlistService:
  image:
    repository: busybox
    tag: '1.36'
  replicas: 1
